<?php

namespace OC\PlatformBundle\Repository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;
/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdvertWithCategories(array $categoryNames){
        
        $list_adverts = $this->createQueryBuilder('a');
        $list_adverts->innerJoin('a.categories', 'c')
                     ->addSelect('c');
        $list_adverts->where($list_adverts->expr()->in('c.name', $categoryNames));
        
        return $list_adverts->getQuery()
                            ->getResult();

    }
}