<?php

namespace OC\PlatformBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert($limit){
        
        $list_apps = $this->createQueryBuilder('a');
        $list_apps->innerJoin('a.advert', 'ad')
                  ->addSelect('ad')
                  ->setMaxResults($limit);
       
        return $list_apps->getQuery()
                         ->getResult();
    }
}
