oc_core_homepage:
    path:     /
    defaults: { _controller: OCCoreBundle:Default:index }
oc_core_view:
    path:      /advert/{id}
    defaults:  
        _controller: OCCoreBundle:Default:view
        page: 1
    requirements:
        page: \d+ 
oc_core_contact:
    path:     /contact
    defaults: { _controller: OCCoreBundle:Default:contact }